markdown: rdiscount
permalink: /:year/:month/:title/
baseurl: /cn
url: http://edguo.github.io/cn
author: 老锅在线
pygments: true
production_url : http://edguo.github.io/cn
name: 老锅在线 
description: 老锅在线 - 中文


